source 'https://rubygems.org'
#gem 'rails', github: 'rails/rails', tag: 'v4.1.0.rc1' #branch: '4-1-stable'
gem 'rails', '4.1'
gem 'dotenv-rails'
gem 'thin'
gem 'paper_trail', '>= 3.0.0.rc2'
gem 'will_paginate', '~> 3.0'
gem 'money-rails'
gem 'activerecord-session_store', github: 'rails/activerecord-session_store'
gem 'sprockets-rails'
gem 'therubyracer'
gem 'mysql2'
#gem 'squeel'
gem 'seedbank'
gem 'scrypt'
gem 'roadie'
gem 'sidekiq'
gem 'sidekiq-limit_fetch'
gem 'sinatra', require: false
gem 'slim'
gem 'lograge'
gem 'logstash-event'
gem 'exception_notification'
gem 'hipchat'
gem 'cancan'
gem 'coffee-rails'
gem 'less-rails'
gem 'uglifier'
gem 'yui-compressor'
gem 'bitcoin-client'
gem 'rotp'
gem 'google-qr'
#gem 'pubnub'
gem 'countries'
gem 'country_select'
gem 'geokit-rails'
gem 'recaptcha', require: 'recaptcha/rails'
gem 'awesome_print'
gem 'newrelic_rpm'
group :development, :test do
  gem 'foreman'
  gem 'byebug'
  gem 'minitest'
  gem 'spring'
  gem 'rspec-rails', '~> 3.0.0.beta'
  gem 'shoulda-matchers'
  gem 'factory_girl_rails', '~> 4.0'
  gem 'brakeman'
  gem 'capistrano', '~> 3.1.0'
  gem 'capistrano-rails', '~> 1.1.0'
  gem 'capistrano-bundler', '~> 1.1.2'
  gem 'capistrano-rvm'
  gem 'capistrano-sidekiq' , github: 'seuros/capistrano-sidekiq'
  gem 'capistrano-newrelic'
end
